shared:
    image: node:8

parameters:
  p1: p1
  p2:
      value: adong
      description: User running build

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - p1: echo $(meta get parameters.p1)
            - p2: echo $(meta get parameters.p2)